config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#about'

  get 'about' => 'static_pages#about'
  get 'hire_me' => 'static_pages#hire_me'
  get 'talks' => 'static_pages#talks'

  get 'contact' => 'static_pages#contact'

  get 'tech' => 'posts#tech_index'
  get 'poetry' => 'posts#poetry_index'
  get 'poetry/:id' => 'posts#poem'
  get 'tech/:id' => 'posts#tech'

  resources :events, only: [:index]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  scope :upcoming, -> { where("date > ?", DateTime.now) }
  scope :past, -> { where("date <= ?", DateTime.now) }

  def talk?
    self.talk
  end

  def workshop?
    self.workshop
  end

  def panel?
    self.panel
  end

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  
  self.per_page = 30
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def tech_index
    @posts = Post.where(tech: true).page(params[:page]).order(created_at: :desc)
    # @posts = Post.where(tech: true).order(created_at: :desc)
  end

  def poetry_index
    @posts = Post.where(poem: true).page(params[:page]).order(created_at: :desc)
    # @posts = Post.where(poem: true).order(created_at: :desc)
  end

  def tech
    @post = Post.where(tech: true).find(params[:id])
  end

  def poem
    @poem = Post.where(poem: true).find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def hire_me
  end

  def talks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/index.html.erb
<article class="cf ph3 ph5-ns pv5 black avenir">
  <div class=" pr4-ns">
    <h1 class="mb3 mt0 lh-title f1 gray">Events</h1>

    <p class="f3 fw4"> These are some of the events I've spoken at or events I've got coming up. There's more information on my <%= link_to "talks & workshops", talks_path, class: "link" %> page.</p>
  </div>

  <div class="">
    <div class="fn f3 fl-ns w-50-ns">
      <h2 class="mb0 pink">Upcoming Events</h2>
      <% @events.upcoming.order(date: :asc).each do |event| %>
        <ul class="list">
          <li class="b"> <%= event.name %> </li>
          <li class="i">
            <% if event.talk? %>
              Talk:
            <% elsif event.workshop? %>
              Workshop:
            <% elsif event.panel? %>
              Panel:
            <% end %>
            <%= event.topic %>
          </li>
          <li> <%= event.date.strftime("%d %b %Y") %></li>
        </ul>
      <% end %>
    </div>

    <div class="fn f3 fl-ns w-50-ns bl-ns bw1 b--black">
      <h2 class="mb0 pl4-ns light-purple">Past Events</h2>
      <% @events.past.order(date: :asc).each do |event| %>
        <ul class="list">
          <li class="b"> <%= event.name %> </li>
          <li class="i">
            <% if event.talk? %>
              Talk:
            <% elsif event.workshop? %>
              Workshop:
            <% elsif event.panel? %>
              Panel:
            <% end %>
            <%= event.topic %>
          </li>
          <li> <%= event.date.strftime("%b %Y") %></li>
        </ul>
      <% end %>
    </div>
  </div>
  
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LolaOdelola</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/tachyons/css/tachyons.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body class="w-100 vh-100">
    <%= render "partials/nav" %>
    <%= yield %>
    <%= render "partials/footer" %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer id="footer" class="bt b--black-10 pv3 tc ph3 pa5-m mt7 mt0-ns avenir">
  <p class="lh-copy tc">
    If you want to contact me, get at me:
    <a href="mailto:me@damilolaodelola.com" class="link dim mr3 b hover-green no-underline black dib">me@damilolaodelola.com</a>
  </p>
  <div class="mt4">
    <a class="link dim mr3 b hover-blue no-underline black dib" href="http://github.com/damzcodes">GitHub</a>
    <a class="link dim mr3 b hover-purple no-underline black dib" href="http://twitter.com/lolaodelola">Twitter</a>
    <a class="link dim mr3 b hover-yellow no-underline black dib" href="https://medium.com/@lolaodelola/">Medium</a>
  </div>
</footer>

app/views/partials/_nav.html.erb
<nav class="pa3 pa4-ns fr avenir">
  <%= link_to "About", about_path, class: "link dim f6 f5-ns dib mr3 b hover-blue no-underline black dib" %>
  <%#= link_to "Hire Me", hire_me_path, class: "link dim f6 f5-ns dib mr3 b hover-green no-underline black dib" %>
  <%= link_to "Talks & Workshops", talks_path, class: "link dim f6 f5-ns dib mr3 b hover-pink no-underline black dib" %>
  <%#= link_to "Events", events_path, class: "link dim f6 f5-ns dib mr3 b hover-navy no-underline black dib" %>
  <%= link_to "Poetry", poetry_path, class: "link dim f6 f5-ns dib mr3 b hover-dark-green no-underline black dib" %>
  <%= link_to "Tech", tech_path, class: "link dim f6 f5-ns dib b hover-purple no-underline black dib" %>
</nav>
<div class="cf"></div>

app/views/posts/poem.html.erb
<article class="pa3 pa5-ns">
  <h1 class="f2 fw1 avenir f-subheadline-ns mb4 black"><%= @poem.title %></h1>
  <p class="gray f6 mb4 ttu tracked">Lola Odelola</p>
  <div class="f4 measure lh-copy">
    <p>
      <%= @poem.body.html_safe %>
    </p>
  </div>

  <a href="/poetry" class="gray f4 dim b link hover-orange">Back to poetry</a>
</article>

<!-- Include Next and Previous buttons -->

app/views/posts/poetry_index.html.erb
<div class="vh-75-ns ph3 ph5-ns">
  <% @posts.each do |post| %>
    <a href= "/poetry/<%= post.id %>" class= "link dim f1-ns f3 avenir fw1-ns dib hover-red pv3 ph2 no-underline black fw4"> <%= post.title %> </a>
    <span class="f1-ns f3 avenir fw1 dib black"> | </span>
  <% end %>
</div>

<div class="fw3 avenir black ph3 ph5-ns">
  <%= will_paginate @posts, previous_label: "<< Previous", next_label: "Next >>"%>
  <%= page_entries_info @posts %>
</div>

app/views/posts/show.html.erb
<article class="pa3 pa5-ns">
  <h1 class="f2 f-subheadline-ns mb4 black"><%= @post.title %></h1>
  <p class="gray f6 mb4 ttu tracked">Lola Odelola</p>
  <div class="f4 f3-ns measure lh-copy">
   <%= @post.body %>
  </div>
</article>

app/views/posts/tech.html.erb
<article class="pa3 pa5-ns">
  <h1 class="f2 f-subheadline-ns mb4 black"><%= @post.title %></h1>
  <p class="gray f6 mb4 ttu tracked">Lola Odelola</p>
  <div class="f4 lh-copy w-75-l">
    <p>
      <%= @post.body.html_safe %>
    </p>
  </div>

  <a href="/tech" class="gray f4 dim b link hover-orange">Back to tech</a>
</article>

<!-- Include Next and Previous buttons -->

app/views/posts/tech_index.html.erb
<div class="vh-75-ns ph3 ph5-ns">
  <% @posts.each do |post| %>
    <a href= "/tech/<%= post.id %>" class= "link dim f1-ns f3 avenir fw1-ns fw4 dib hover-red pv3 ph2 no-underline black"> <%= post.title %> </a>
    <span class="f1-ns f3 avenir fw1 dib black"> | </span>
  <% end %>
</div>

<div class="fw3 avenir black ph3 ph5-ns">
  <%= will_paginate @posts, previous_label: "<< Previous", next_label: "Next >>"%>
  <%= page_entries_info @posts %>
</div>

app/views/static_pages/about.html.erb
<article class="cf ph3 ph5-ns pv5 black avenir">
  <header class="fn fl-ns w-25-ns pr4-ns">
    <h1 class="mb3 mt0 lh-title f1 yellow">Lola Odelola</h1>
  </header>
  <div class="fn fl-ns w-50-ns f4">
    <p class="lh-copy measure mt4 mt0-ns">
      Hi! I’m Lola, I write poems and build web things.
      Like most toddlers, I learnt to write when I was about 3 and haven’t stopped since. 18yrs after conquering pen holding, I accidentally fell in love with coding and have been on a quest to learn and teach as much as possible.
    </p>
    <p class="lh-copy measure">
      I‘m a published poet via my self ( <em>#000000</em> ) and Eyewear Poetry ( <em>Lost and Found</em> ). <em>Lost and Found</em> was selected as the 2016 Poetry Book Society's spring pamphlet. I run an organisation, <a href="http://blackgirl.tech" class="link b no-underline hover-red dib black hover-red courier">blackgirl.tech</a>, that aims to provide a safe space for girls and women of colour to learn more about tech and how to code.
    </p>
    <p class="lh-copy measure">
      If you'd like me to speak at something, <a href="mailto:me@damilolaodelola.com" class="link dim b hover-grey no-underline black dib">get in touch!</a> I'm open to speaking about ruby, rails, diversity and inclusion in tech, poetry, writing, and probably other stuff. Hear me ramble on the internet on <a href="https://soundcloud.com/blackgirltech/sets/lost-in-the-source" class="link dim b hover-green no-underline black dib">Lost in the Source</a> or you can read my tech or poetry ramblings. Here's some stuff other people have said about me:
      </p>
      <a class="link dib dim black b hover-red no-underline" href="https://www.buzzfeed.com/tolanishoneye/blackgirlmagic?utm_term=.jv5vnXOL4v#.sf2XJbNY9X">Buzzfeed</a> |
      <a class="link dim b hover-blue no-underline black dib" href="https://soundcloud.com/naomi-simon-show/caribbean-takeaway-bhm-iv">20something Podcast</a> |
      <a class="link dim b hover-pink no-underline black dib" href="https://www.projectada.co.uk/tag/black-girl-tech/">Project Ada</a> |
      <a class="link dim b hover-orange no-underline black dib" href="https://trueafrica.co/lists/13-different-black-british-women-amazing-things/">13 Black British Women Doing Amazing Things</a> |
      <a class="link dim b hover-purple no-underline black dib" href="https://davepoems.wordpress.com/2016/02/11/damilola-odelola-lost-found/">A Review of Lost and Found</a>
  </div>
</article>

app/views/static_pages/bios.html.erb
<article class="cf ph3 ph5-ns h-75-ns pv5 black avenir">
  <header class="fn fl-ns w-25-ns pr4-ns">
    <h2 class="mb3 mt0 lh-title f1 dark-pink">Bios</h2>
<!--     <a href="#" class="link dib dim black b hover-red no-underline">CV</a>
 -->  </header>
  <div class="fn fl-ns w-50-ns f3">
    <h3> < 250 chars</h3>
    <p class="lh-copy measure mt4 mt0-ns">
      Lola is a ruby developer, poet and founder of blackgirl.tech. She’s passionate about diversifying the industry and making it more inclusive and safe. Lola is the author of two poetry pamphlets and freelances as an anti-cheesecake activist.
    </p>

    <h3> 500 chars</h3>
    <p class="lh-copy measure mt4 mt0-ns">
      Lola is a ruby developer, poet and founder of blackgirl.tech. She’s passionate about diversifying the industry and making it more inclusive and safe. Lola is the author of two poetry pamphlets and freelances as an anti-cheesecake activist. Lola is a ruby developer, poet and founder of blackgirl.tech. She’s passionate about diversifying the industry and making it more inclusive and safe. Lola is the author of two poetry pamphlets and freelances as an anti-cheesecake activist.
    </p>

    <h3> 500 chars</h3>
    <p class="lh-copy measure mt4 mt0-ns">
      Lola is a ruby developer, poet and founder of blackgirl.tech. She’s passionate about diversifying the industry and making it more inclusive and safe. Lola is the author of two poetry pamphlets and freelances as an anti-cheesecake activist. Lola is a ruby developer, poet and founder of blackgirl.tech. She’s passionate about diversifying the industry and making it more inclusive and safe. Lola is the author of two poetry pamphlets and freelances as an anti-cheesecake activist. Lola is a ruby developer, poet and founder of blackgirl.tech. She’s passionate about diversifying the industry and making it more inclusive and safe. Lola is the author of two poetry pamphlets and freelances as an anti-cheesecake activist. Lola is a ruby developer, poet and founder of blackgirl.tech. She’s passionate about diversifying the industry and making it more inclusive and safe. Lola is the author of two poetry pamphlets and freelances as an anti-cheesecake activist.
    </p>
  </div>
</article>

app/views/static_pages/hire_me.html.erb
<article class="cf ph3 ph5-ns pv5 black avenir">
  <header class="fn fl-ns w-25-ns pr4-ns">
    <h2 class="mb3 mt0 lh-title f1 dark-pink">Hire Me</h2>
    <%= link_to "Talks & Workshops", talks_path, class: "link dim b hover-pink no-underline black dib" %>
    <%= link_to "Upcoming & Past Events", events_path, class: "link dim b hover-navy no-underline black dib" %>
<!--     <a href="#" class="link dib dim black b hover-red no-underline">CV</a>
 -->  </header>
  <div class="fn fl-ns w-75-ns f3">
    <p class="lh-copy measure mt4 mt0-ns">
      I am available for freelance consulting and speaking engagements in London and remote. Software engineering and web development is my day job and I have three years experience in the field. Through this work and my contributions to diversty and inclusion in technology with my organisation, <a class="link dim b hover-red courier no-underline black dib" href="http://www.blackgirl.tech">blackgirl.tech</a>.
      For more information, you can email <a href="mailto:me@damilolaodelola.com" class="link dim b hover-green no-underline black dib">me@damilolaodelola.com</a>.
    </p>
  </div>
</article>

  <div class="w-100 fn ph3 ph5-ns black avenir f3 cf">
    <h2 class="navy">Services</h2>
    <div class="mb2">
      <h4>Company culture &amp; HR process:</h4>
      <ul class="">
        <li class=" pb4 pb0-ns fn fl-ns w-50-ns pr3-ns">
          <em class="green">Policy analysis and development:</em><br><br> I’ll look through your current staff
          handbook, contracts, and policies to identify places where there may be
          hidden prejudices, work with your HR team to ensure your policies enable
          and protect your employees and have diversity at the center.
        </li>
        <li class=" pb4 pb0-ns fn fl-ns w-50-ns pl3-ns">
          <em class="green">Culture analysis and development:</em><br><br> I can analyse the organisation’s work culture by
          looking at employee satisfaction, the primary ways employees socialise with
          each other, and create an environment that makes sure employees are safe
          and are not only giving the most, but getting the most from work.
        </li>
      </ul>
    </div>

    <div class="mb2">
      <h4 class="mt1-ns">Diverse recruitment &amp; hiring:</h4>
      <ul>
        <li class=" pb4 pb0-ns fn fl-ns w-50-ns pr3-ns">
          <em class="green">Job description analysis:</em><br><br> I can work with your organisation to ensure that your
          job descriptions and adverts are not biased and are as inviting as possible.
          This includes analysing your job description for keywords and phrases,
          ensuring that the qualifications are in line with the role, improving current job
          descriptions to be more inviting.
        </li>
        <li class=" pb4 pb0-ns fn fl-ns w-50-ns pl3-ns">
          <em class="green">Hiring process review:</em><br><br> I’ll be working with your organisation to improve the
          hiring process to ensure that the best candidates are not discriminated during
          the process. This includes analysing the interview and testing process to
          identify weaknesses, implementing the best practices for interview process for
          the organisation and potential employee, reviewing testing process and
          implementing best practices for code testing to ensure that applicants are
          given the best chance to succeed.
        </li>
      </ul>
    </div>

    <div class="mb2">
      <h4 class="">Company audit &amp; reports</h4>
      <p class="mt0">I can conduct a series of audits and create a series of reports on the following:</p>
      <ul>
        <li class=" pb4 pb0-ns fn fl-ns w-third-ns pr3-ns">
          <em class="green">Company and team make up:</em><br><br> % of men, women, ethnic minorities, LGBTQIA,
          uni-educated, class background, ability &amp; the intersections of each e.g. % of
          white, heterosexual, able-bodied men in the tech team.
        </li>
        <li class=" pb4 pb0-ns fn fl-ns w-third-ns pl3-ns">
          <em class="green">Analysis of employee progression:</em><br><br> An audit and report of how often
          employees progress through the company, who progresses the most, who is
          least likely to progress.
        </li>
        <li class=" pb4 pb0-ns fn fl-ns w-third-ns pl3-ns">
          <em class="green">Salary analysis:</em><br><br> An audit and report of different starting salaries, how many and often employees get payrises, by how much employees’ pay rises are bumped.
        </li>
      </ul>
    </div>
  </div>

app/views/static_pages/talks.html.erb
<article class="cf ph3 ph5-ns pv5 black avenir">
  <div class="fn w-100-ns pr4-ns">
    <h1 class="mb3 mt0 lh-title f1 dark-green">Talks &amp; Workshops</h1>

    <p class="f3 fw4"> If you would like to invite me to give a talk or lead a workshop, you can email <a class="link hover-yellow b black" href="mailto:me@damilolaodelola.com">me@damilolaodelola.com</a>. I am comfortable talking about writing, the writing process, rails, ruby, gadgets, diversity and inclusion, jobs, and being a junior developer. I'm not limited to this list, so if you have a topic that you'd like to hear me speak on, you can still pitch it. <span class="light-purple white">I don't give talks or lead workshops between Friday sunset and Saturday sunset.</span> Some of my talks are listed below, I also host the <a class="link hover-red b black" href="https://soundcloud.com/lostinthesource">Lost in the Source Podcast</a> and the co-host of <a class="link hover-blue b black" href="https://soundcloud.com/backslashpod">backslash</a>.</p>
  </div>

  <div class="fn w-50-ns f3">
    <h2 class="mb0">Finding Your Dream Job</h2>
    <p class="mt1 f4">Many people feel like they can't interview potential employers however, it's very important to ask employers some key questions before you accept a job. In this talk I present on what you should be looking for to ensure that you are adequately supported in a new role. My talk in the video is from 19:56.</p>
    <a href="https://skillsmatter.com/skillscasts/9865-london-ruby-lightning-talks" class="link ba bw1 br3 pa1 light-blue hover-white hover-bg-light-blue b--light-blue"> Video </a>
    <a href="https://s3.eu-west-2.amazonaws.com/lolaodelola/slides/five_job_tips_pdf.pdf" class="link ba bw1 br3 pa1 light-blue hover-white hover-bg-light-blue b--light-blue mh2"> Slides </a>
    <a href="https://soundcloud.com/lostinthesource/lostinthesource-ep2-do-dream-jobs-exist" class="link ba bw1 br3 pa1 light-blue hover-white hover-bg-light-blue b--light-blue"> Podcast </a>
  </div>
  
</article>